name: Sync with stashapp/stash
on:
  workflow_dispatch:

jobs:

  sync-upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get the latest version of Stash
      id: stash_version
      run: |
        echo ::set-output name=STASH_VERSION::$(curl -sX GET "https://api.github.com/repos/stashapp/stash/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GHUB_TOKEN }}
        custom_tag: ${{ steps.stash_version.outputs.STASH_VERSION }}
        tag_prefix: